version: "3.9"

services:
  database:
    image: postgres
    container_name: won-games-container
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin666
      - POSTGRES_DB=won-games
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
